# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: BREAN Jeremy
title: Cloud Engineer / Cloud Architect / Cloud FinOps
email: jeremy.brean@sysid.fr
website: https://github.com/FatalDaron

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  FatalDaron
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: jbrean
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
additional_links:
# - title: Link
#   icon: 
#   url: 
# - title: 
#   icon: 
#   url: 

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/JBR_CV.png
about_content: | 
  Self-taught and passionate, I have 24 years of experience in the field of IT, 6 years as a DEVOPS engineer and 4 years as a Cloud Engineer at Société Générale. I love working in a team and having a good relationship, I would like to put myself at the service of your company.

  I am most skilled in: <mark>AWS</mark>, <mark>Ansible</mark>, <mark>Terraform</mark>, <mark>Kubernetes</mark>, <mark>Devops</mark> and <mark>Linux</mark>

content:

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Software Factory
        link: Société Générale
        link_text: societegenerale.com/fr
        sub_title: Cloud Engineer / Cloud FinOps / Cloud Architect
        caption: February 2018 - Present
        quote: >
          Management of CI/CD tools and the development of tool allowing automation 
        description: | 
            Working in a Software Factory, my activity was the management of CI / CD tools and the development of tools allowing the automation and integration of client applications on Public / Private clouds

            My activity within the Private Cloud:
            - Management of CI/CD tools (jenkins/Nexus/Sonartype)
            - CI/CD automation via libraries (Ansible, Groovy, Python)
            - Automation of deployments on VMs and kubernetes (Ansible, YAML)

            My activity within the public cloud:
            - Management of CI/CD tools (Gitlab/Openshift/Cloudbees/Nexus/Sonartype)
            - CI/CD automation via libraries (Terraform, Ansible, Groovy, Python)
            - Automation of deployments on AWS and kubernetes (Terraform, Ansible, Groovy, Python)

            Used skill : <mark>AWS</mark>, <mark>Ansible</mark>, <mark>Terraform</mark>, <mark>Groovy</mark> and <mark>Python</mark>

      - layout: left
        title: Technical Referent
        link: Société Générale
        link_text: societegenerale.com/fr
        sub_title: Devops Ingineer
        caption: march 2016 - February 2018
        quote: >
          Management of a CD automation team
        description: | 
            Within a 20-person technical office, my mission was to bring my knowledge and expertise.
            Creation of a automate solution  the deployment of applications on VMs without going through a technical office.
            This solution has improved the time to market and reduced operating costs
            Develop in Ansible/Python/Groovy, it was exploited through Ansible TOWER/AWS and Jenkins

            Used skill : <mark>Team Management</mark>, <mark>Ansible</mark>, <mark>Groovy</mark> and <mark>Python</mark>

      - layout: left
        title: Operations Support
        link: Société Générale
        link_text: societegenerale.com/fr
        sub_title: Product Engineer
        caption: May 2015 - March 2016
        quote: >
          Analysis of changes/incidents and cost optimization
        description: | 
            The objective of my mission within the Operation Support department was the analysis of the accidentology data of all the application scopes.
            These analyses resulted in transverse action plans to correct all the problems encountered and to reduce operating costs and make applications more reliable.

            Used skill : <mark>BMC Patrol</mark>, <mark>SAP BusinessObjects</mark>, <mark>Macro VBA</mark> and <mark>Microsoft Excel</mark>

      - layout: left
        title: Project Manager
        link: Société Générale
        link_text: societegenerale.com/fr
        sub_title: Intergrateur Project Manager
        caption: January 2012 - May 2015
        quote: >
          Project Manager was to coordinate and integrate all new applications or infrastructures
        description: | 
            My mission was that Intergrateur Project Manager was to coordinate and integrate all new applications or infrastructures.
            Positioned on different projects simultaneously, my mission was to generate a schedule and coordinate all the stakeholders according to a specification provided by the clients.
            During my mission, 33 projects were finalized.   
            Example of project implemented: <a href="https://www.societegenerale.com/fr/actualites/newsroom/strategie-5">Digital For All</a>

            Used skill : <mark>Project management</mark> and <mark>solution architect</mark>

      - layout: left
        title: Administrator system and network
        link: Société Générale
        link_text: societegenerale.com/fr
        sub_title: Production Engineer
        caption: May 2009 - January 2012
        quote: >
          Production engineer in a technical office
        description: | 
            Within a technical office, my mission was to provide support and expertise on all applications within my scope.
            My objectives were to manage all customer requests, assist users and monitor incidents, administer and monitor all applications within my scope and carry out a 24/7 on-call.

            Used skill : <mark>Linux</mark>, <mark>Windows Server</mark>, <mark>Bash</mark>, <mark>Python</mark> and <mark>Opensource application</mark>

      - layout: left
        title: System and Network Administrator
        link: Adhesia
        link_text: adhesia.fr
        caption: October 2004 - October 2012
        description: | 
            Used skill : <mark>Windows Server</mark>, <mark>Active Directory</mark>, <mark>Exchange</mark> and <mark>LAN/WAN</mark>

      - layout: left
        title: System and Network Administrator
        link: Banque Populaire
        link_text: banquepopulaire.fr
        caption: December 2008 - April 2009
        description: | 
            Used skill : <mark>Linux</mark>, <mark>HAProxy</mark>, <mark>Postfix</mark> and <mark>Cisco</mark>

      - layout: left
        title: Product Ingineer
        link: BNP Paribas
        link_text: mabanque.bnpparibas
        caption: October 2006 - November 2008
        description: | 
            Used skill : <mark>Infovista</mark> and <mark>BMC Patrol</mark>

      - layout: left
        title: System and Network Administrator
        link: SIEMENS
        link_text: siemens.com
        caption: May 2001 - October 2004
        description: | 
            Used skill : <mark>Unix</mark>, <mark>Linux</mark> and <mark>Language C</mark>


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Puteaux - Lycée Agora 
        caption: 1997 - 1999
        sub_title: BTS, Conception de Produits Industriels

      - layout: left
        title: Cergy - Lycée Polyvalent Jules Verne
        caption: 1995 - 1997
        sub_title: BAC STI , Génie Mécanique

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
